package routes

const routeNameDiagnostics = "diagnostics"
const routeNameHeartbeat = "heartbeat"
const routeNameSayError = "say-error"
const routeAuthPostLogin = "auth-post-login"
const routeAuthPostLogout = "auth-post-logout"
const routeAuthPostRegisterUser = "auth-post-register-user"
const routeAuthPostDetailsValidate = "auth-post-details-validate"
const routeAuthPostRefreshToken = "auth-post-refresh-token"
const routeAuthPostCheckToken = "auth-post-check-token"
const routeAuthPostRecoverPassword = "auth-post-recover-password"
const routeAuthPostResetPassword = "auth-post-reset-password"
const routeAuthPostAnswers = "auth-post-answers"

const routeNameAppDiagnostics = "app-diagnostics"
const routeNameAppHeartbeat = "app-heartbeat"
const routeNameAppSayError = "app-say-error"

const pathHeartbeat = "/"
const pathSayError = "/error"
const pathLogin = "/login"
const pathLogout = "/logout"
const pathRefreshToken = "/refresh-token"
const pathRegDetailsValidate = "/reg-details-validate"
const pathRegUser = "/register-user"
const pathRecoverPassword = "/recover-password"
const pathResetPassword = "/reset-password"
const pathCheckToken = "/check-token"
const pathAuthPostAnswers = "/security-answers"

const pathPrefixV1 = "/v1"
const pathPrefixV2 = "/v2"
const appName = "ms-login"
